#!/usr/bin/python3
# -*- coding:utf-8 -*-
#author=von-fan
# Generated by Django 2.2.2 on 2019-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True, default='2019-06-29 00:40:35.000000'),
            preserve_default=False,
        ),
    ]
